services:
  database-postgres:
    container_name: finance-ctrl-database
    build:
      context: ../
      dockerfile: .docker/postgresql/Dockerfile
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${DATABASE_TZ}
    networks:
      - finance-ctrl-network-api
    restart: on-failure
    tty: true
    env_file:
       - .env

  finance-ctrl-api:
    container_name: finance-ctrl-api
    build:
      context: ../
      dockerfile: .docker/java/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    working_dir: /var/www/finance-ctrl-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ../:/var/www/finance-ctrl-api
    networks:
      - finance-ctrl-network-api
    depends_on:
      - database-postgres
    links:
      - database-postgres
    tty: true
    env_file:
      - .env
networks:
  finance-ctrl-network-api:
    name: finance-ctrl-network
